services:
  notifier:
    build: .
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      YOUR_CHAT_ID: ${YOUR_CHAT_ID}
      RECEIVER_EMAIL_ADDRESS: ${RECEIVER_EMAIL_ADDRESS}
      SENDER_EMAIL_ADDRESS: ${SENDER_EMAIL_ADDRESS}
      SENDER_EMAIL_PASSWORD: ${SENDER_EMAIL_PASSWORD}